services:
  server:
    build: .
    volumes:
      - './dist:/home/node/code'
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
    - e-learning-db:/var/lib/postgresql/data

volumes:
  e-learning-db: