version: '3.8'

services:
  server:
    command: npm run dev:start
    volumes:
      - ./src:/home/node/code
      - /home/node/code/node_modules
    environment:
      - NODE_ENV=developement
    ports:
      - "3000:3000"