services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
    - db:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
  server:
    build: 
      context: .
      dockerfile: ${DOCKER_FILE}
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy

networks:
  network:
    driver: bridge

volumes:
  db: